[phases.setup]
nixPkgs = ["ffmpeg", "python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = ["python -m pip install --user -r requirements.txt"]

[start]
cmd = "gunicorn application:application --bind 0.0.0.0:$PORT"
