[phases.setup]
nixPkgs = ["ffmpeg", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "gunicorn application:application --bind 0.0.0.0:$PORT"
