[phases.setup]
nixPkgs = ["ffmpeg", "python311"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "gunicorn application:application --bind 0.0.0.0:$PORT"
